# Build properties
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

  app:
    encoding: @project.build.sourceEncoding@
    java.source: @java.version@
    java.target: @java.version@
